{
  "defectsList" : [ {
    "title" : "Product defects",
    "status" : "FAILED",
    "defects" : [ {
      "uid" : "d015ef1df622248c",
      "failure" : {
        "message" : "AssertionError: assert 1 == 2",
        "stackTrace" : "self = <Work.test_A.Test_A instance at 0x10d0afb48>\n\n    def test_error_case(self):\n        allure.attach(\"描述\",\"this a error case!\")\n>       assert 1 == 2\nE       assert 1 == 2\n\nWork/test_A.py:32: AssertionError"
      },
      "testCases" : [ {
        "uid" : "a05fd6a7adba3110",
        "name" : "Test_A.test_error_case",
        "title" : "Test error case",
        "time" : {
          "start" : 1501841725297,
          "stop" : 1501841725318,
          "duration" : 21
        },
        "severity" : "NORMAL",
        "status" : "FAILED"
      } ]
    } ]
  }, {
    "title" : "Test defects",
    "status" : "BROKEN",
    "defects" : [ ]
  } ]
}